### ISSUE TITLE
Fix fetch and gather startup

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckan-docker-dcatapit#10]
fetch and gather need the very same configuration files that ckan uses, and that are created in the entrypoint scripts.
They also need redis running, and that  DB is initialized.

Add the proper dependencies (or checks via scripts) to wait for the congif file to be ready before running the consumers.

**Comment by lpasquali** [comment]
Hello @etj I have fixed all you requested, I also remembered and verified that there are some problems with the cron as you told me, and I fixed also this in the PR [here](https://github.com/geosolutions-it/ckan-docker-dcatapit/pull/14)

**Comment by lpasquali** [comment]
hello @randomorder I assigned PR to @etj and put this into review

**Comment by lpasquali** [comment]
@randomorder code has been merged and then deployed this can be closed
