### ISSUE TITLE
Containers for `gather` and `fetch`

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckan-docker-dcatapit#5]
As per the diagram in #1, containers for the `gather_consumer` and the `fetch_consumer` processes are still missing.
They are part of the `ckanext-harvest` setup.

Doc here:
    https://github.com/ckan/ckanext-harvest#setting-up-the-harvesters-on-a-production-server
 
They share the very same code and extensions of CKAN, so they may be either run inside the ckan container, or have their own.
They communicate with the central ckan via redis, and need access to DB, solr and filesystem (config, storage)

It would be good to have them log to file; also, if we make such files reside on the host filesystem it would be great.

**Comment by lpasquali** [comment]
implemented in PR #9
