### ISSUE TITLE
Harvester run command

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckan-docker-dcatapit#6]
The harvesting setup requires a process to be run with cron every 5 minutes

Doc [here](https://github.com/ckan/ckanext-harvest#:~:text=Once%20we%20have%20the%20two%20consumers%20running%20and%20monitored).

> Once we have the two consumers running and monitored, we just need to create a cron job that will run the run harvester command periodically. To do so, edit the cron table with the following command (it may ask you to choose an editor):
> ```bash
> sudo crontab -e -u ckan
> ```
> Note that we are running this command as the same user we configured the processes to be run with (ckan in our example).
> 
> Paste this line into your crontab, again replacing the paths to paster and the ini file with yours:
> 
> ```cron
> # m  h  dom mon dow   command
> */15 *  *   *   *     /usr/lib/ckan/default/bin/ckan -c /etc/ckan/default/ckan.ini harvester run
> ```

**Comment by lpasquali** [comment]
implemented in PR #9
