### ISSUE TITLE
DB externalization

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckan-docker-dcatapit#8]
In case this compose is installed in an architecture where a DB is already provided, we should make it easily configurable (i.e. we dont want to run the container with PG, and we should be able to set in the `.env` file the access credentials to the external DB).

**Comment by randomorder** [comment]
waiting to have a call with the client to discuss if we can use docker-compose or not

**Comment by tdipisa** [comment]
After the call with the client we had on March 3rd, we agreed to not use docker and proceed with a manual installation.
